---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04
      #box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
suites:
  - name: default
    run_list:
      - recipe[base::default]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes: {
      "base": {
        "pam": {
          "sshd": {
            "conf": [
              'auth required pam_yubico.so mode=client try_first_pass ldap_uri=ldap://ldap.newmediadenver.com/ ldapdn=ou=people,dc=ldap,dc=newmediadenver,dc=com user_attr=cn yubi_attr=departmentNumber debug',
              '@include common-auth',
              'account    required     pam_nologin.so',
              '@include common-account',
              '@include common-session',
              'session    optional     pam_motd.so # [1]',
              'session    optional     pam_mail.so standard noenv # [1]',
              'session    required     pam_limits.so',
              'session    required     pam_env.so # [1]',
              'session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale',
              '@include common-password'
            ]
          }
        }
      },
      "fail2ban": {
        "services": {
          "ssh": {
            "enabled": "true",
            "port": "ssh",
            "filter": "sshd",
            "logpath": "/var/log/auth.log",
            "maxretry": "6"
          },
          "xinetd-fail": {
            "enabled": "true",
            "port": "all",
            "filter": "xinetd-fail",
            "logpath": "/var/log/daemon.log",
            "maxretry": "6",
            "banaction": "iptables-multiport-log"
          },
          "ssh-ddos": {
            "enabled": "true",
            "port": "ssh",
            "filter": "sshd-ddos",
            "logpath": "/var/log/auth.log",
            "maxretry": "6",
            "banaction": "iptables-multiport-log"
          }
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
  - name: ldap
    run_list:
      - recipe[base::ldap]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes:
  - name: yubico
    run_list:
      - recipe[base::yubico]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes: {
      "base": {
        "yubico": {
          "authfile": '/etc/yubikey_mappings',
          "users": [
            'vagrant:ccccccdivlul',
            'cyberswat:ccccccdivlul'
          ]
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
  - name: yubico-ldap
    run_list:
      - recipe[base::ldap]
      - recipe[base::yubico]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes: {
      "base": {
        "pam": {
          "sshd": {
            "conf": [
              'auth required pam_yubico.so mode=client try_first_pass ldap_uri=ldap://ldap.newmediadenver.com/ ldapdn=ou=people,dc=ldap,dc=newmediadenver,dc=com user_attr=cn yubi_attr=departmentNumber debug',
              '@include common-auth',
              'account    required     pam_nologin.so',
              '@include common-account',
              '@include common-session',
              'session    optional     pam_motd.so # [1]',
              'session    optional     pam_mail.so standard noenv # [1]',
              'session    required     pam_limits.so',
              'session    required     pam_env.so # [1]',
              'session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale',
              '@include common-password'
            ]
          }
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
