---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04
      #box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
suites:
  - name: default
    run_list:
      - recipe[chef-client::delete_validation]
      - recipe[chef-client::config]
      - recipe[chef-client::service]
    attributes:
  - name: ldap
    run_list:
      - recipe[base::ldap]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes:
  - name: yubico
    run_list:
      - recipe[base::yubico]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes: {
      "base": {
        "yubico": {
          "authfile": '/etc/yubikey_mappings',
          "users": [
            'vagrant:ccccccdivlul',
            'cyberswat:ccccccdivlul'
          ]
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
  - name: tfa
    run_list:
      - recipe[base::ldap]
      - recipe[base::yubico]
    data_bags_path: "~/nmd-chef/data_bags"
    attributes: {
      "base": {
        "yubico": {
          "id": "15916",
          "key": "iqXJ1Moo70WCI4wrxBpniqvPDiw=",
          "authfile": '/etc/yubikey_mappings',
          "debug": true,
          "users": [
            'vagrant:ccccccdivlul',
            'cyberswat:ccccccdivlul'
          ]
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
