---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04
      # box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu-14.04
      # box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
suites:
  - name: default
    run_list:
      - recipe[nmdbase::default]
    data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
    attributes: {
      "fail2ban": {
        "services": {
          "ssh": {
            "enabled": "true",
            "port": "ssh",
            "filter": "sshd",
            "logpath": "/var/log/auth.log",
            "maxretry": "6"
          },
          "xinetd-fail": {
            "enabled": "true",
            "port": "all",
            "filter": "xinetd-fail",
            "logpath": "/var/log/daemon.log",
            "maxretry": "6",
            "banaction": "iptables-multiport-log"
          },
          "ssh-ddos": {
            "enabled": "true",
            "port": "ssh",
            "filter": "sshd-ddos",
            "logpath": "/var/log/auth.log",
            "maxretry": "6",
            "banaction": "iptables-multiport-log"
          }
        }
      },
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
  - name: ldap
    run_list:
      - recipe[nmdbase::ldap]
    data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
    attributes:
  - name: yubico
    run_list:
      - recipe[nmdbase::yubico]
    data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
    attributes: {
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
  - name: yubico-ldap
    run_list:
      - recipe[nmdbase::ldap]
      - recipe[nmdbase::yubico]
    data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
    attributes: {
      "openssh": {
        "server": {
          "use_p_a_m": "yes",
          "challenge_response_authentication": "yes",
          "password_authentication": "yes"
        }
      }
    }
