language: ruby
rvm:
- 1.9.3
- 2.0.0
before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
install: bundle install --without=integration
script: CODECLIMATE_REPO_TOKEN=61a0d4eb07d7694fc74c8098020a724884bc8425c89d307687230ae2164f928d
  bundle exec rake test
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 61a0d4eb07d7694fc74c8098020a724884bc8425c89d307687230ae2164f928d
notifications:
  hipchat:
env:
  global:
    secure: HpSDH+KIhtHADEpU5F7spgtkL7NXMfOcd5oFusnpKC/l3bvJeP5nytl2yxQ7kxhHrjU2jpUUomZD1JFP1vb8zTyAn2ll0tWAqhB2rarcPhAchEnVB6a1ryG+kRIQKrIy+/AH/P/jdq2L+HKWYos85nVCCMkKzp4HsmSVKJgjcqQ=
