language: ruby
rvm:
- 1.9.3
- 2.0.0
before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
<<<<<<< HEAD
      secure: bVhXUZh/7CwFdGNKorB6xNteNujxo4Jdbcy9cs/PhIdLd30dKupiXcqK4TuLw2JID7rcUTybqnHVIBG9GvIxvT1Eh+dMGZe++O49T+/IUb5w8TqO2gjlMf6RTcQGmC5X00zmfJj6P2ZvzgJd3hWrEYTlvbcsujXd/Ucm6W3dcOg=
install: script/cached-bundle install --without integration --deployment
env:
  global:
    secure: V+xtzKssxyQJlEB9USMYtvj5SZfvguYvLESow4hSrgMZ+H5ZDKsgReCvXVFmxMv+c1V7iA2JmVIh0eD00T6PJEP2iwhgSXCr5sn425IBGzeWUP/ekoX1KLPIAdH254LDR/R68Ag17RmzyY8svWvZK7yVOtyyPHfGaiocDVAsPGI=
=======
      secure: "CEDnwELcfSncKfslFz3HY1K6CZqqOrMs+3XTtf/MvUOsOT7lxBpn+XE0k1u/KBvYmlqPE+oAd9f2et9C2MzjR3uCggPN5ulXmepQ6SaYGyWsc5rE8eDj4MJeAFC5mqyanNe43p1SyzDNXa8sYpkIqFcPG7csQ+rUqzMjjVxHLfQ="
      language: ruby
install: bundle install --without integration --deployment
cache:
  directories:
  - vendor/bundle
>>>>>>> Updating hipchat token.
