language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
      secure: bVhXUZh/7CwFdGNKorB6xNteNujxo4Jdbcy9cs/PhIdLd30dKupiXcqK4TuLw2JID7rcUTybqnHVIBG9GvIxvT1Eh+dMGZe++O49T+/IUb5w8TqO2gjlMf6RTcQGmC5X00zmfJj6P2ZvzgJd3hWrEYTlvbcsujXd/Ucm6W3dcOg=
install: script/cached-bundle install --without integration --deployment
env:
  global:
    secure: V+xtzKssxyQJlEB9USMYtvj5SZfvguYvLESow4hSrgMZ+H5ZDKsgReCvXVFmxMv+c1V7iA2JmVIh0eD00T6PJEP2iwhgSXCr5sn425IBGzeWUP/ekoX1KLPIAdH254LDR/R68Ag17RmzyY8svWvZK7yVOtyyPHfGaiocDVAsPGI=
