source "https://rubygems.org"

gem "test-kitchen", "~> 1.0"
gem "kitchen-vagrant"
gem "berkshelf", "~> 2.0"
gem "vagrant-wrapper"
gem "rake", "~> 10.1.1"
gem "foodcritic", "~> 0.2.0"
gem "rubocop"
gem "rspec"
