# encoding: utf-8
require 'serverspec'

include Serverspec::Helper::Exec
include Serverspec::Helper::DetectOS
RSpec.configure do |c|
  c.before :all do
    c.path = '/usr/bin'
  end
end
if os[:family] == 'RedHat'
  describe file('/etc/sysconfig/iptables') do
    it { should be_file }
    it { should be_mode 644 }
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    its(:content) { should match '^# This file generated by Chef.(.*)?' }
  end
end
