require 'serverspec'

include Serverspec::Helper::Exec
include Serverspec::Helper::DetectOS

RSpec.configure do |c|
  c.before :all do
    c.path = '/usr/bin'
  end
end

describe file('/etc/ssh/sshd_config') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should match '^# This file was generated by Chef for*.+$' }
  its(:content) { should match '^# Do NOT modify this file by hand!$' }
  its(:content) { should match '^ChallengeResponseAuthentication yes$' }
  its(:content) { should match '^UsePAM yes$' }
  its(:content) { should match '^PasswordAuthentication yes$' }
end

describe file('/etc/apt/sources.list.d/yubico-stable-precise.list') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should match 'deb http://ppa.launchpad.net/yubico/stable/ubuntu precise main' }
  its(:content) { should match 'deb-src http://ppa.launchpad.net/yubico/stable/ubuntu precise main' }
end

describe package('libpam-yubico') do
  it { should be_installed }
end
